<a href="https://colab.research.google.com/github/saimathura/deeplearning-MDSC302/blob/main/22233_assignment1_302(P).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

Looking in indexes: https://download.pytorch.org/whl/cu117


# this is how we load torch

In [ ]:
import torch


tensor([[0.1408, 0.2777, 0.9214],
        [0.8106, 0.6912, 0.0472],
        [0.9036, 0.3181, 0.3884],
        [0.1669, 0.6987, 0.1120],
        [0.4021, 0.8143, 0.6773]])


# Checking if torch is working

In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6906, 0.3530, 0.1909],
        [0.2151, 0.7281, 0.3451],
        [0.3578, 0.9091, 0.2307],
        [0.5157, 0.8234, 0.3325],
        [0.6335, 0.2656, 0.7367]])


#checking if GPU is working?


In [ ]:
torch.cuda.is_available()

True

#PyTorch has two primitives to work with data: torch.utils.data.DataLoader and torch.utils.data.Dataset. Dataset stores the samples and their corresponding labels, and DataLoader wraps an iterable around the Dataset.

In [ ]:
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [ ]:
import numpy as np

In [ ]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [ ]:
np_array = np.array(data)

In [ ]:
x_np = torch.from_numpy(np_array)

In [ ]:
x_ones = torch.ones_like(x_data)
print(f'ones Tensor : \n {x_ones} \n')

x_rand = torch.rand_like(x_data,dtype = torch.float)
print(f'ones Tensor : \n {x_rand} \n')

ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

ones Tensor : 
 tensor([[0.7058, 0.3217],
        [0.8810, 0.3141]]) 



In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor :{rand_tensor},ones_tensor = {ones_tensor} , zeros_tensor = {zeros_tensor}')

Random Tensor :tensor([[0.7882, 0.8934, 0.9130],
        [0.8850, 0.8790, 0.4850]]),ones_tensor = tensor([[1., 1., 1.],
        [1., 1., 1.]]) , zeros_tensor = tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
tensor = torch.rand(3,4)
print(f"shape of Tensor: {tensor.shape} ,Datatype of tensor : {tensor.dtype},Device where the tensor is stored {tensor.device}")

shape of Tensor: torch.Size([3, 4]) ,Datatype of tensor : torch.float32,Device where the tensor is stored cpu


In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [ ]:
tensor  = torch.ones(4,4)
print(f'First row: {tensor[0]} ,first column: {tensor[:,0]}')
print(f"last col: {tensor[:,-1]}")
tensor[:,1] = 0
print(tensor)
print(f'First row: {tensor[0]} ,first column: {tensor[:,0]}')
print(f"secomd col: {tensor[...,1]}")


First row: tensor([1., 1., 1., 1.]) ,first column: tensor([1., 1., 1., 1.])
last col: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
First row: tensor([1., 0., 1., 1.]) ,first column: tensor([1., 1., 1., 1.])
secomd col: tensor([0., 0., 0., 0.])


In [ ]:
t1 = torch.cat([tensor,tensor,tensor], dim = 1 )
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y1,y2,y3)

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
